### PR TITLE
Add \externalMentorName macro to support external mentor thesis.

### PR DESCRIPTION
**Pull request by Lancern**
This PR addresses issue #45 .

A new macro, `\externalMentorName` is added. When defined, a new external thesis cover will be generated. When not defined, normal cover will be generated. Users can control which cover to generate by defining this macro.

The usage of this new macro has been given in the source comment.

### CODE REVIEW

**Comment by spencerwooo** [comment]
这个不太完全一样，校外的封面不是简单加一行校外指导教师就可以，上下左右的高度都要调整下…

| Word | LaTeX |
|:-:|:-:|
| image | image |

**Comment by Lancern** [comment]
比起 word 模板来，LaTeX 模板的页面内容好像整体下移了一点

**Comment by spencerwooo** [comment]
我在调整了……（导师还在催我，别急）

**Comment by spencerwooo** [comment]
@Lancern macOS 试一下？康康对的准不准 hhh

**Comment by Lancern** [comment]
比较精准了

| Word | LaTeX |
|-------|-------|
|  图片 | 图片 |

**Comment by spencerwooo** [comment]
okk，合并！

**Pull request merged**
